import { chapter as chapter1 } from "./content/chapters/01-workflow";
import { chapter as chapter2 } from "./content/chapters/02-camera";
import { chapter as chapter3 } from "./content/chapters/03-shooting";
import { chapter as chapter4 } from "./content/chapters/04-selection";
import { chapter as chapter5 } from "./content/chapters/05-editing";
import { chapter as chapter6 } from "./content/chapters/06-archive";
import { chapter as chapter7 } from "./content/chapters/07-delivery";
import { chapter as chapter8 } from "./content/chapters/08-assessment";
export type { Chapter, Section } from "./content/types";
export const chapters = [
  chapter1,
  chapter2,
  chapter3,
  chapter4,
  chapter5,
  chapter6,
  chapter7,
  chapter8,
];

export const workflow = [
  [
    "接到任务",
    "负责人",
    "确认主题、时间地点、主办单位、出席人员、平台、时长与截止时间。",
    "只接到一句“拍个视频”就出发。",
    "形成可确认的任务单。",
  ],
  [
    "明确需求",
    "负责人 / 剪辑",
    "确认横竖屏、叙事重点、审核人及发布权限。",
    "拍完才发现需要竖屏。",
    "需求与交付规格得到确认。",
  ],
  [
    "前期准备",
    "拍摄成员",
    "查看流程与场地，分配机位，试录灯光和收音，检查电池存储。",
    "关键动作无人负责。",
    "镜头清单、设备与备选方案就绪。",
  ],
  [
    "活动拍摄",
    "拍摄成员",
    "保完整关键动作，记录全景、人物、细节和真实反应。",
    "只追求素材数量，漏掉揭牌。",
    "关键环节有效覆盖且不干扰现场。",
  ],
  [
    "素材汇总",
    "素材管理员",
    "保留原始目录，按机位汇总，核对文件数与播放。",
    "上传未完成就清空卡。",
    "至少有可用备份及交接清单。",
  ],
  [
    "素材筛选",
    "剪辑 / 负责人",
    "六维判断、标注 A/B/C/X，核实人物与语意。",
    "清晰就用，忽视身份与权限。",
    "精选与限制素材均有依据。",
  ],
  [
    "剪辑制作",
    "剪辑成员",
    "粗剪结构、精剪节奏，处理声音字幕与色彩。",
    "灰片直出，音乐掩盖发言。",
    "可完整观看且事实准确的交审版。",
  ],
  [
    "审核修改",
    "审核 / 剪辑",
    "按时间码反馈，逐项改动并记录版本。",
    "口头通过后继续覆盖文件。",
    "明确版本通过正式审核。",
  ],
  [
    "成片归档",
    "负责人 / 管理员",
    "保存成片、工程、素材、封面文案及批准记录。",
    "只有一个发布链接。",
    "接手者能找到文件并打开工程。",
  ],
];
export const shootChecks = [
  "已确认活动主题、时间、地点与主办单位",
  "已核实出席人员和姓名职务来源",
  "已确认发布平台、时长和交付期限",
  "已分配关键环节与主辅机位",
  "已检查电池、存储、镜头与收音",
  "已试录检查频闪、曝光、白平衡与对焦",
  "已确认现场权限和限制区域",
  "已安排素材汇总与备份负责人",
];
export const deliveryChecks = [
  "活动名称、时间地点与新闻事实准确",
  "人物姓名职务及字幕逐字核实",
  "叙事、反应镜头与实际过程一致",
  "无黑帧、严重抖动、失焦与异常频闪",
  "同期声清楚，音量与声画同步正常",
  "Log 已正确还原，多机位色彩一致",
  "画幅、分辨率、帧率与编码符合交付要求",
  "字幕安全区域及手机观看已检查",
  "素材授权、隐私、保密与音乐版权已核对",
  "学校审核流程、发布权限和批准版本已确认",
  "成片已完整播放并核对文件",
  "工程、原始素材、文案与审核记录已归档",
];
export const practiceChecks = [
  "已复述任务与交付时间",
  "已制定参数和例外说明",
  "已分配关键镜头及备用机位",
  "已选定符合事实的重要画面",
  "已完成十二个素材判断",
  "已规划背景—行动—结果结构",
  "已完成命名与文件整理",
  "已选择导出规格并说明理由",
  "已完成三线审核并提交批准流程",
];
export type Case = {
  title: string;
  scene: string;
  quality: string;
  person: string;
  value: string;
  issue: string;
  grade: string;
  reason: string;
  risk: string;
  action: string;
  visual: string;
};
export const cases: Case[] = [
  {
    title: "完整的揭牌瞬间",
    scene: "艺术展开幕，主机位连续拍摄。",
    quality: "清晰稳定，曝光正常。",
    person: "嘉宾自然完成揭牌，身份已核实。",
    value: "直接呈现关键仪式。",
    issue: "无已知限制，授权已确认。",
    grade: "A",
    reason: "关键动作完整，信息准确，技术及权限满足要求。",
    risk: "剪短后可能丢失动作起止。",
    action: "保留前后余量，作为叙事主镜头。",
    visual: "reveal",
  },
  {
    title: "轻微抖动的观众镜头",
    scene: "同一场开幕活动的观众聆听。",
    quality: "短暂轻微抖动，主体清楚。",
    person: "状态自然，使用范围已确认。",
    value: "补充现场氛围。",
    issue: "不是关键事实镜头。",
    grade: "B",
    reason: "真实合规，有补充价值但有轻微技术瑕疵。",
    risk: "过度稳定导致画面变形。",
    action: "选稳定区间或适度稳定后使用。",
    visual: "audience",
  },
  {
    title: "持续失焦的发言",
    scene: "会议发言，有另一机位完整记录。",
    quality: "面部持续失焦。",
    person: "身份核实，发言正常。",
    value: "内容重要但可由清晰机位替代。",
    issue: "主体辨识困难。",
    grade: "C",
    reason: "严重技术问题且有同一真实过程的替代素材。",
    risk: "锐化不能修复失去的细节。",
    action: "改用清晰机位，保留原件作为记录。",
    visual: "blur",
  },
  {
    title: "屏幕出现内部名单",
    scene: "会前调试投影。",
    quality: "画面清楚，姓名电话可读。",
    person: "无人正面出镜。",
    value: "仅作为环境过渡。",
    issue: "含未经许可公开的内部个人信息。",
    grade: "X",
    reason: "敏感信息公开风险优先于画面质量。",
    risk: "泄露个人信息。",
    action: "隔离报告；经负责人确认处理后再评估替代镜头。",
    visual: "screen",
  },
  {
    title: "眨眼瞬间被停格",
    scene: "嘉宾致辞，同机位有自然连续画面。",
    quality: "清晰稳定。",
    person: "截取时明显闭眼。",
    value: "人物介绍。",
    issue: "停格不恰当地代表人物状态。",
    grade: "C",
    reason: "有真实自然替代镜头，不宜用偶然瞬间代表人物。",
    risk: "造成不准确印象。",
    action: "选择同一情境中自然画面，不伪造表情。",
    visual: "speaker",
  },
  {
    title: "人物字幕张冠李戴",
    scene: "两位嘉宾先后发言。",
    quality: "画面与声音清楚。",
    person: "画面为甲，字幕写乙的姓名职务。",
    value: "重要发言。",
    issue: "身份对应错误。",
    grade: "X",
    reason: "当前版本信息不真实，不能发布。",
    risk: "误传身份与观点。",
    action: "核实名单与时间码，纠正并复核后重新评级。",
    visual: "caption",
  },
  {
    title: "会前握手移到签约后",
    scene: "素材来自同一天的会前问候。",
    quality: "稳定清晰。",
    person: "自然握手，身份准确。",
    value: "被剪成签约成功后的庆祝。",
    issue: "真实动作被赋予不存在的因果。",
    grade: "X",
    reason: "上下文改变造成虚假行为意义。",
    risk: "观众误解协议形成过程。",
    action: "恢复真实上下文，改用实际发生的签约后镜头。",
    visual: "hands",
  },
  {
    title: "舞台队形完整呈现",
    scene: "文艺演出群舞高潮。",
    quality: "安全全景，曝光和灯光正常。",
    person: "队形完整，授权已确认。",
    value: "展示节目主体与空间关系。",
    issue: "无已知问题。",
    grade: "A",
    reason: "景别匹配内容，真实完整且合规。",
    risk: "过多裁切会破坏队形。",
    action: "保留必要全景时长，与同场细节衔接。",
    visual: "stage",
  },
  {
    title: "构图稍空的会场",
    scene: "会议开始前，主题横幅可读。",
    quality: "清晰，空白略多。",
    person: "无可识别人物。",
    value: "交代地点与主题。",
    issue: "内容单一，不适合作主叙事。",
    grade: "B",
    reason: "适合作为真实环境补充。",
    risk: "长时间使用造成信息停滞。",
    action: "短暂建立空间，必要时适度裁切。",
    visual: "hall",
  },
  {
    title: "志愿者真实协助",
    scene: "校园服务现场，连续记录帮助搬运。",
    quality: "主体清楚，运动稳定。",
    person: "自然交流，拍摄发布意愿已确认。",
    value: "行动清楚，体现服务过程。",
    issue: "无已知问题。",
    grade: "A",
    reason: "真实行动具有内容价值，技术与授权可靠。",
    risk: "剪辑过短可能看不清动作。",
    action: "保留行为和互动，避免空洞配乐替代信息。",
    visual: "service",
  },
  {
    title: "颁奖被前景完全遮挡",
    scene: "颁奖过程中其他拍摄者挡住主体。",
    quality: "遮挡占据主要画面。",
    person: "无法看清交接动作。",
    value: "关键动作未被有效记录，另一机位可用。",
    issue: "无有效内容。",
    grade: "C",
    reason: "严重遮挡，不能承担该叙事任务。",
    risk: "观众无法理解人物与动作。",
    action: "调取辅机位；复盘站位，不要求正式参与者重演。",
    visual: "block",
  },
  {
    title: "旧活动掌声冒充本次反应",
    scene: "上学期会议的观众鼓掌。",
    quality: "清晰稳定。",
    person: "出席人员与本次不一致。",
    value: "计划插到本次发言之后。",
    issue: "跨时间拼接且没有资料标注。",
    grade: "X",
    reason: "让观众误认为不存在的现场反应。",
    risk: "制造虚假支持与因果。",
    action: "弃用这种拼接，使用本次真实反应；资料用途另行标注审核。",
    visual: "audience",
  },
];
export const questions = [
  {
    q: "常规活动的团队默认设置是？",
    a: [
      "4K / 30fps / 通常 1/60 秒",
      "1080P / 60fps / 固定 1/500 秒",
      "所有设备使用最高帧率",
    ],
    correct: 0,
    why: "常规统一 4K、30fps，1/60 秒为基准；频闪与慢动作需要测试例外。",
    chapter: 1,
  },
  {
    q: "现场出现 LED 频闪，应该怎样处理？",
    a: [
      "坚持 1/60 不变",
      "现场试录并测试防频闪、快门等设置，记录例外",
      "只提高锐化",
    ],
    correct: 1,
    why: "灯光调制与电网频率会影响频闪，必须根据实际灯光测试回看。",
    chapter: 1,
  },
  {
    q: "Log 与 LUT 的关系是？",
    a: [
      "Log 是一种 LUT 文件",
      "任何品牌都可以混用同一技术 LUT",
      "Log 是编码曲线，LUT 是颜色映射，需匹配输入",
    ],
    correct: 2,
    why: "曲线和色域不同，技术转换需与具体素材模式匹配。",
    chapter: 1,
  },
  {
    q: "多人颁奖时，首先要保证什么？",
    a: ["背景尽可能虚化", "关键人物和交接动作清楚完整", "每秒换一个机位"],
    correct: 1,
    why: "景深、构图和机位都应服务于关键事实，不只追求虚化。",
    chapter: 2,
  },
  {
    q: "嘉宾身份无法核实时如何处理？",
    a: ["先猜职务发布", "只看画面是否清晰", "暂停相关身份使用，向负责人核实"],
    correct: 2,
    why: "姓名职务必须与实际人物一致，不能发布后再核实。",
    chapter: 3,
  },
  {
    q: "把会前握手剪成签约后的庆祝，应如何评级？",
    a: ["A，画面清晰", "B，稍作调色即可", "X，改变上下文造成虚假因果"],
    correct: 2,
    why: "真实素材也可以因错误拼接产生虚假行为意义，当前版本不能发布。",
    chapter: 3,
  },
  {
    q: "本地工程复制给同事后打不开素材，最可能是？",
    a: ["工程未包含或未关联完整媒体", "文件名字太短", "一定需要购买会员"],
    correct: 0,
    why: "工程通常包含编辑信息与媒体引用，交接需检查关联素材和重连。",
    chapter: 4,
  },
  {
    q: "J-cut 的典型特征是？",
    a: ["声音比对应画面更早进入", "声音晚于画面结束才开始", "字幕全部靠边"],
    correct: 0,
    why: "下一镜头声音先于画面进入，可自然引出场景或人物。",
    chapter: 4,
  },
  {
    q: "什么时候可以把文件命名为 FINAL_已审核？",
    a: ["第一次导出后", "明确版本确认通过审核后", "剪辑者觉得满意时"],
    correct: 1,
    why: "FINAL 只用于确认审核通过的最终版本，新改动须重新版本与审核。",
    chapter: 5,
  },
  {
    q: "网盘上传显示完成后，还应该做什么？",
    a: [
      "立即删除所有原件",
      "核对数量大小，抽检播放并验证接收权限",
      "只发一句“传完了”",
    ],
    correct: 1,
    why: "任务完成提示不能代替完整性、可用性与访问验证。",
    chapter: 5,
  },
  {
    q: "MP4 与 H.264 分别代表什么？",
    a: ["都是分辨率", "帧率和码率", "封装格式与视频编码"],
    correct: 2,
    why: "封装承载流，编码压缩图像；分辨率、帧率和码率是不同参数。",
    chapter: 6,
  },
  {
    q: "交付检查表全部勾选意味着？",
    a: [
      "自动取得学校发布批准",
      "已具备提交审核或交付条件，仍需正式批准",
      "可以跳过版权检查",
    ],
    correct: 1,
    why: "检查器是自查工具，不能代替学校审核与发布权限。",
    chapter: 6,
  },
];
export const folders = [
  "01_原始素材",
  "02_筛选素材",
  "03_音频资料",
  "04_剪辑工程",
  "05_审核版本",
  "06_最终成片",
  "07_封面与文案",
];
export const fileTasks = [
  {
    source: "相机卡工作副本 001.mp4",
    folder: 0,
    name: "20261008_校园活动_A机位_001.mp4",
    tip: "日期、活动、机位、序号齐全；卡内原件保留。",
  },
  {
    source: "同期声录音.wav",
    folder: 2,
    name: "20261008_校园活动_同期声_001.wav",
    tip: "声音文件放入音频资料，并记录对应机位和时间。",
  },
  {
    source: "第一次交审视频.mp4",
    folder: 4,
    name: "校园活动_V01_待审.mp4",
    tip: "未通过审核不能使用 FINAL。",
  },
  {
    source: "已获批准的最终视频.mp4",
    folder: 5,
    name: "校园活动_FINAL_已审核.mp4",
    tip: "只有明确批准的版本进入最终成片。",
  },
  {
    source: "剪映工程文件",
    folder: 3,
    name: "校园活动_V02_工程",
    tip: "工程与关联媒体说明一起交接。",
  },
  {
    source: "发布封面.png",
    folder: 6,
    name: "校园活动_封面.png",
    tip: "封面与发布文案统一管理。",
  },
];
export const sources = [
  ["大疆 · 按型号选择官方 LUT", "https://www.dji.com/lut"],
  [
    "索尼 · 什么是 LUT",
    "https://www.sony.com/zh-cn/electronics/support/articles/00197011",
  ],
  [
    "松下 · V-Log 转换与 LUT",
    "https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/support/lut/",
  ],
  ["剪映 · 官方客户端与当前功能", "https://www.capcut.cn/"],
  ["百度网盘 · 官方客户端与账号权益", "https://pan.baidu.com/"],
];
